/// Concrete typed filter builders generated by macros
/// Each builder implements only the operators valid for their field type
use crate::{
    FilterBuilder, IndexMap,
    filters::{BoolFieldOps, DateTimeFieldOps, EnumFieldOps, FloatFieldOps, IntFieldOps, StringFieldOps},
    query_structure::PrismaValue,
};
use query_core::ArgumentValue;

/// String field filter - allows text operations
pub struct StringFilter<'a, B> {
    pub builder: &'a mut B,
    pub field_name: &'static str,
}

impl<'a, B: FilterBuilder> StringFieldOps for StringFilter<'a, B> {
    fn eq<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("equals".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn not<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("not".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn contains<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("contains".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn starts_with<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("startsWith".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn ends_with<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("endsWith".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn in_list<T: Into<PrismaValue>>(self, values: Vec<T>) -> Self {
        let list: Vec<ArgumentValue> = values.into_iter().map(|v| ArgumentValue::Scalar(v.into())).collect();
        let mut map = IndexMap::new();
        map.insert("in".to_string(), ArgumentValue::List(list));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn not_in_list<T: Into<PrismaValue>>(self, values: Vec<T>) -> Self {
        let list: Vec<ArgumentValue> = values.into_iter().map(|v| ArgumentValue::Scalar(v.into())).collect();
        let mut map = IndexMap::new();
        map.insert("notIn".to_string(), ArgumentValue::List(list));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn gt<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("gt".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn gte<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("gte".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn lt<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("lt".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn lte<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("lte".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }
}

/// Int field filter - allows numeric comparisons
pub struct IntFilter<'a, B> {
    pub builder: &'a mut B,
    pub field_name: &'static str,
}

impl<'a, B: FilterBuilder> IntFieldOps for IntFilter<'a, B> {
    fn eq<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("equals".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn not<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("not".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn gt<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("gt".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn gte<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("gte".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn lt<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("lt".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn lte<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("lte".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn in_list<T: Into<PrismaValue>>(self, values: Vec<T>) -> Self {
        let list: Vec<ArgumentValue> = values.into_iter().map(|v| ArgumentValue::Scalar(v.into())).collect();
        let mut map = IndexMap::new();
        map.insert("in".to_string(), ArgumentValue::List(list));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn not_in_list<T: Into<PrismaValue>>(self, values: Vec<T>) -> Self {
        let list: Vec<ArgumentValue> = values.into_iter().map(|v| ArgumentValue::Scalar(v.into())).collect();
        let mut map = IndexMap::new();
        map.insert("notIn".to_string(), ArgumentValue::List(list));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }
}

/// Boolean field filter - only eq/not
pub struct BoolFilter<'a, B> {
    pub builder: &'a mut B,
    pub field_name: &'static str,
}

impl<'a, B: FilterBuilder> BoolFieldOps for BoolFilter<'a, B> {
    fn eq<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("equals".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn not<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("not".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }
}

/// Enum field filter - eq/not/in (enum-aware)
pub struct EnumFilter<'a, B> {
    pub builder: &'a mut B,
    pub field_name: &'static str,
}

impl<'a, B: FilterBuilder> EnumFieldOps for EnumFilter<'a, B> {
    fn eq<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("equals".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn not<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("not".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn in_list<T: Into<PrismaValue>>(self, values: Vec<T>) -> Self {
        let list: Vec<ArgumentValue> = values.into_iter().map(|v| ArgumentValue::Scalar(v.into())).collect();
        let mut map = IndexMap::new();
        map.insert("in".to_string(), ArgumentValue::List(list));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn not_in_list<T: Into<PrismaValue>>(self, values: Vec<T>) -> Self {
        let list: Vec<ArgumentValue> = values.into_iter().map(|v| ArgumentValue::Scalar(v.into())).collect();
        let mut map = IndexMap::new();
        map.insert("notIn".to_string(), ArgumentValue::List(list));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }
}

/// Float field filter - supports numeric comparisons
pub struct FloatFilter<'a, B> {
    pub builder: &'a mut B,
    pub field_name: &'static str,
}

impl<'a, B: FilterBuilder> FloatFieldOps for FloatFilter<'a, B> {
    fn eq<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("equals".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn not<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("not".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn gt<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("gt".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn gte<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("gte".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn lt<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("lt".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn lte<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("lte".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn in_list<T: Into<PrismaValue>>(self, values: Vec<T>) -> Self {
        let list: Vec<ArgumentValue> = values.into_iter().map(|v| ArgumentValue::Scalar(v.into())).collect();
        let mut map = IndexMap::new();
        map.insert("in".to_string(), ArgumentValue::List(list));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn not_in_list<T: Into<PrismaValue>>(self, values: Vec<T>) -> Self {
        let list: Vec<ArgumentValue> = values.into_iter().map(|v| ArgumentValue::Scalar(v.into())).collect();
        let mut map = IndexMap::new();
        map.insert("notIn".to_string(), ArgumentValue::List(list));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }
}

/// DateTime field filter - supports temporal comparisons
pub struct DateTimeFilter<'a, B> {
    pub builder: &'a mut B,
    pub field_name: &'static str,
}

impl<'a, B: FilterBuilder> DateTimeFieldOps for DateTimeFilter<'a, B> {
    fn eq<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("equals".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn not<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("not".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn gt<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("gt".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn gte<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("gte".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn lt<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("lt".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn lte<T: Into<PrismaValue>>(self, value: T) -> Self {
        let mut map = IndexMap::new();
        map.insert("lte".to_string(), ArgumentValue::Scalar(value.into()));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn in_list<T: Into<PrismaValue>>(self, values: Vec<T>) -> Self {
        let list: Vec<ArgumentValue> = values.into_iter().map(|v| ArgumentValue::Scalar(v.into())).collect();
        let mut map = IndexMap::new();
        map.insert("in".to_string(), ArgumentValue::List(list));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }

    fn not_in_list<T: Into<PrismaValue>>(self, values: Vec<T>) -> Self {
        let list: Vec<ArgumentValue> = values.into_iter().map(|v| ArgumentValue::Scalar(v.into())).collect();
        let mut map = IndexMap::new();
        map.insert("notIn".to_string(), ArgumentValue::List(list));
        self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        self
    }
}

/// Relation field filter - allows some/every/none/is/is_not operations
pub struct RelationFilter<'a, B, WB> {
    pub builder: &'a mut B,
    pub field_name: &'static str,
    pub _phantom: std::marker::PhantomData<WB>,
}

impl<'a, B: FilterBuilder, WB: Default + FilterBuilder> RelationFilter<'a, B, WB> {
    pub fn some<F>(mut self, f: F) -> Self
    where F: FnOnce(&mut WB) {
        let mut nested = WB::default();
        f(&mut nested);
        self.add_nested_op("some", nested);
        self
    }

    pub fn every<F>(mut self, f: F) -> Self
    where F: FnOnce(&mut WB) {
        let mut nested = WB::default();
        f(&mut nested);
        self.add_nested_op("every", nested);
        self
    }

    pub fn none<F>(mut self, f: F) -> Self
    where F: FnOnce(&mut WB) {
        let mut nested = WB::default();
        f(&mut nested);
        self.add_nested_op("none", nested);
        self
    }

    pub fn is<F>(mut self, f: F) -> Self
    where F: FnOnce(&mut WB) {
        let mut nested = WB::default();
        f(&mut nested);
        self.add_nested_op("is", nested);
        self
    }

    pub fn is_not<F>(mut self, f: F) -> Self
    where F: FnOnce(&mut WB) {
        let mut nested = WB::default();
        f(&mut nested);
        self.add_nested_op("isNot", nested);
        self
    }

    fn add_nested_op(&mut self, op: &str, nested: WB) {
        let args = nested.build();
        if !args.is_empty() {
            let mut map = IndexMap::new();
            map.insert(op.to_string(), ArgumentValue::Object(args));
            self.builder.add_arg(self.field_name.to_string(), ArgumentValue::Object(map));
        }
    }
}
