// Generated by Saola CLI. DO NOT EDIT.
pub mod enums;
#[allow(unused_imports)]
pub use enums::*;

mod user_dir;
pub use user_dir::mod_exports::*;
mod post_dir;
pub use post_dir::mod_exports::*;
mod profile_dir;
pub use profile_dir::mod_exports::*;

#[allow(unused_imports)]
pub mod prelude {
    pub use ::saola_core::prelude::*;
}

#[allow(unused_imports)]
pub mod builders {
    pub use super::post_dir::builders::*;
    pub use super::profile_dir::builders::*;
    pub use super::user_dir::builders::*;
}

#[derive(Clone)]
pub struct SaolaClient(pub ::saola_core::SaolaClient);
impl std::ops::Deref for SaolaClient {
    type Target = ::saola_core::SaolaClient;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl ::saola_core::transaction::QueryExecutorProvider for SaolaClient {
    fn executor(&self) -> std::sync::Arc<dyn ::saola_core::query_core::QueryExecutor + Send + Sync> {
        self.0.executor()
    }
    fn query_schema(&self) -> std::sync::Arc<::saola_core::schema::QuerySchema> {
        self.0.query_schema()
    }
    fn tx_id(&self) -> Option<&::saola_core::query_core::TxId> {
        self.0.tx_id()
    }
}

#[derive(Clone)]
pub struct Transaction(pub ::saola_core::transaction::Transaction);
impl std::ops::Deref for Transaction {
    type Target = ::saola_core::transaction::Transaction;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl ::saola_core::transaction::QueryExecutorProvider for Transaction {
    fn executor(&self) -> std::sync::Arc<dyn ::saola_core::query_core::QueryExecutor + Send + Sync> {
        self.0.executor()
    }
    fn query_schema(&self) -> std::sync::Arc<::saola_core::schema::QuerySchema> {
        self.0.query_schema()
    }
    fn tx_id(&self) -> Option<&::saola_core::query_core::TxId> {
        self.0.tx_id()
    }
}

pub async fn client() -> ::saola_core::Result<SaolaClient> {
    Ok(SaolaClient(
        ::saola_core::SaolaClient::new(
            r#"datasource db {
  provider = "sqlite"
  url      = "file:/home/ravi/Documents/projects/saola/example-app/dev.db"
}

model User {
  id        String    @id @default(cuid())
  email     String    @unique
  name      String
  isActive  Boolean   @default(true)
  score     Float     @default(0.0)
  level     Int       @default(1)
  posts     Post[]
  profile   Profile?
  createdAt DateTime  @default(now())
}

model Post {
  id        String    @id @default(cuid())
  title     String
  content   String?
  published Boolean   @default(false)
  userId    String
  user      User      @relation(fields: [userId], references: [id])
  createdAt DateTime  @default(now())
}

model Profile {
  id     String @id @default(cuid())
  bio    String?
  userId String @unique
  user   User   @relation(fields: [userId], references: [id])
}
"#,
            "file:/home/ravi/Documents/projects/saola/example-app/dev.db",
        )
        .await?,
    ))
}
#[allow(dead_code)]
impl SaolaClient {
    pub fn user(&self) -> user_dir::builders::UserQuery {
        user_dir::builders::UserQuery {
            provider: std::sync::Arc::new(self.clone()),
        }
    }
    pub fn post(&self) -> post_dir::builders::PostQuery {
        post_dir::builders::PostQuery {
            provider: std::sync::Arc::new(self.clone()),
        }
    }
    pub fn profile(&self) -> profile_dir::builders::ProfileQuery {
        profile_dir::builders::ProfileQuery {
            provider: std::sync::Arc::new(self.clone()),
        }
    }
    pub async fn transaction<F, Fut, T>(&self, callback: F) -> ::saola_core::Result<T>
    where
        F: FnOnce(Transaction) -> Fut,
        Fut: std::future::Future<Output = ::saola_core::Result<T>>,
    {
        self.0.transaction(|tx| callback(Transaction(tx))).await
    }
}
#[allow(dead_code)]
impl Transaction {
    pub fn user(&self) -> user_dir::builders::UserQuery {
        user_dir::builders::UserQuery {
            provider: std::sync::Arc::new(self.clone()),
        }
    }
    pub fn post(&self) -> post_dir::builders::PostQuery {
        post_dir::builders::PostQuery {
            provider: std::sync::Arc::new(self.clone()),
        }
    }
    pub fn profile(&self) -> profile_dir::builders::ProfileQuery {
        profile_dir::builders::ProfileQuery {
            provider: std::sync::Arc::new(self.clone()),
        }
    }
}
