//! Utility functions for macro code generation

use syn::{GenericArgument, PathArguments, Type};

/// Extract the innermost type from a potentially generic type
/// E.g., Option<String> -> String, Vec<i32> -> i32
pub fn get_inner_type(ty: &Type) -> String {
    match ty {
        Type::Path(tp) => {
            let segment = tp.path.segments.last().unwrap();
            match &segment.arguments {
                PathArguments::AngleBracketed(args) => {
                    if let Some(GenericArgument::Type(inner_ty)) = args.args.first() {
                        get_inner_type(inner_ty)
                    } else {
                        segment.ident.to_string()
                    }
                }
                _ => segment.ident.to_string(),
            }
        }
        _ => "String".to_string(),
    }
}

/// Detect field type and return the appropriate filter builder type name
/// Returns (filter_builder_name, trait_name) for type-safe filters
pub fn get_filter_type(ty: &Type) -> Option<(&'static str, &'static str)> {
    let type_name = get_inner_type(ty);

    match type_name.as_str() {
        "String" => Some(("StringFilter", "StringFieldOps")),
        "i32" | "i64" | "u32" | "u64" => Some(("IntFilter", "IntFieldOps")),
        "bool" => Some(("BoolFilter", "BoolFieldOps")),
        "f32" | "f64" => Some(("FloatFilter", "FloatFieldOps")),
        "DateTime" => Some(("DateTimeFilter", "DateTimeFieldOps")),
        _ => {
            // Default to EnumFilter for unknown types (enums generated by schema)
            Some(("EnumFilter", "EnumFieldOps"))
        }
    }
}
